# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

r_github_packages:
  - SymbolixAU/googleway
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
